### ISSUE TITLE
Feature request: verbose output for ups/downs notation

### ISSUE THREAD

**Issue by TallKite** [m-yac/xen-calc#16]
If we input 13\41, we get vM3, we should get downmajor 3rd as well.
Similar to how color notation has both y3 and yo 3rd.
Often the "possible English name" seems to include this. But it's not merely possible, it's the standard name. So probably remove it from the possible English category.

**Comment by m-yac** [comment]
This (and more) is done in m-yac/microtonal-utils@d571c57010dfddd54fa108346da409f99d3ac466 and 1957e629c026d3eaaa15fac002b9d792602bc3dc. Now:
- The verbose ups-and-downs name is shown next to each abbreviated ups-and-downs symbol
- Verbose ups-and-downs notation is valid input (e.g. "downmajor 3rd \ 53")
- Did-you-mean text is shown for all ups-and-downs notation (e.g. "down major 3 \ 12" is corrected to "downmajor 3rd \ 12" – and not "minor 3rd \ 12")
- The "(Possible) English name" field will never contain any "ups" or "downs" (e.g. just "12-EDO major third") and uses "neutral" instead of "mid" (e.g. "24-EDO neutral third") to reflect the way I personally refer to these intervals.

Thanks for the suggestion!
